version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: test-database
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'printjson(db.runCommand({connectionStatus: 1}))'"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-backend-container
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - mongodb

  frontend:
    image: bookstore-frontend
    container_name: my-frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongodb-data:
